version: 2.1
defaults: &defaults
  machine:
    image: circleci/classic:edge

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: ./scripts/ci
          when: always

workflows:
  version: 2
  default-workflow:
    jobs:
      - test

      # - publish:
      #     <<: *prepost
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: /^release-v.*/
