version: 2.1
defaults: &defaults
  machine:
    image: ubuntu-2404:2024.05.1

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: ./scripts/ci
          when: always
      - store_artifacts:
          path: ~/video

workflows:
  version: 2
  default-workflow:
    jobs:
      - test

      # - publish:
      #     <<: *prepost
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: /^release-v.*/
